<?php
require_once('classes/realestate.com.au/PageMiner.php');
$miner = new PageMiner('data/html');

$miner->mine('Abbotsbury', 2);
$miner->mine('Abbotsford', 2);
$miner->mine('Acacia Gardens', 2);
$miner->mine('Agnes Banks', 2);
$miner->mine('Airds', 2);
$miner->mine('Alexandria', 2);
$miner->mine('Alfords Point', 2);
$miner->mine('Allambie Heights', 2);
$miner->mine('Allawah', 2);
$miner->mine('Ambarvale', 2);
$miner->mine('Annandale', 2);
$miner->mine('Annangrove', 2);
$miner->mine('Arcadia', 2);
$miner->mine('Arncliffe', 2);
$miner->mine('Arndell Park', 2);
$miner->mine('Artarmon', 2);
$miner->mine('Ashbury', 2);
$miner->mine('Ashcroft', 2);
$miner->mine('Ashfield', 2);
$miner->mine('Asquith', 2);
$miner->mine('Auburn', 2);
$miner->mine('Austral', 2);
$miner->mine('Avalon Beach', 2);
$miner->mine('Badgerys Creek', 2);
$miner->mine('Balgowlah Heights', 2);
$miner->mine('Balgowlah', 2);
$miner->mine('Balmain East', 2);
$miner->mine('Balmain', 2);
$miner->mine('Bangor', 2);
$miner->mine('Banksia', 2);
$miner->mine('Banksmeadow', 2);
$miner->mine('Bankstown Aerodrome', 2);
$miner->mine('Bankstown', 2);
$miner->mine('Barangaroo', 2);
$miner->mine('Barden Ridge', 2);
$miner->mine('Bardia', 2);
$miner->mine('Bardwell Park', 2);
$miner->mine('Bardwell Valley', 2);
$miner->mine('Barra Brui', 2);
$miner->mine('Bass Hill', 2);
$miner->mine('Baulkham Hills', 2);
$miner->mine('Bayview', 2);
$miner->mine('Beacon Hill', 2);
$miner->mine('Beaconsfield', 2);
$miner->mine('Beaumont Hills', 2);
$miner->mine('Beecroft', 2);
$miner->mine('Belfield', 2);
$miner->mine('Bella Vista', 2);
$miner->mine('Bellevue Hill', 2);
$miner->mine('Belmore', 2);
$miner->mine('Belrose', 2);
$miner->mine('Berala', 2);
$miner->mine('Berkshire Park', 2);
$miner->mine('Berowra Creek', 2);
$miner->mine('Berowra Heights', 2);
$miner->mine('Berowra Waters', 2);
$miner->mine('Berowra', 2);
$miner->mine('Berrilee', 2);
$miner->mine('Beverley Park', 2);
$miner->mine('Beverly Hills', 2);
$miner->mine('Bexley North', 2);
$miner->mine('Bexley', 2);
$miner->mine('Bickley Vale', 2);
$miner->mine('Bidwill', 2);
$miner->mine('Bilgola Beach', 2);
$miner->mine('Bilgola Plateau', 2);
$miner->mine('Birchgrove', 2);
$miner->mine('Birrong', 2);
$miner->mine('Blackett', 2);
$miner->mine('Blacktown', 2);
$miner->mine('Blair Athol', 2);
$miner->mine('Blairmount', 2);
$miner->mine('Blakehurst', 2);
$miner->mine('Bligh Park', 2);
$miner->mine('Bondi Beach', 2);
$miner->mine('Bondi Junction', 2);
$miner->mine('Bondi', 2);
$miner->mine('Bonnet Bay', 2);
$miner->mine('Bonnyrigg Heights', 2);
$miner->mine('Bonnyrigg', 2);
$miner->mine('Bossley Park', 2);
$miner->mine('Botany', 2);
$miner->mine('Bow Bowing', 2);
$miner->mine('Box Hill', 2);
$miner->mine('Bradbury', 2);
$miner->mine('Breakfast Point', 2);
$miner->mine('Bringelly', 2);
$miner->mine('Bronte', 2);
$miner->mine('Brooklyn', 2);
$miner->mine('Brookvale', 2);
$miner->mine('Bundeena', 2);
$miner->mine('Bungarribee', 2);
$miner->mine('Burwood Heights', 2);
$miner->mine('Burwood', 2);
$miner->mine('Busby', 2);
$miner->mine('Cabarita', 2);
$miner->mine('Cabramatta West', 2);
$miner->mine('Cabramatta', 2);
$miner->mine('Caddens', 2);
$miner->mine('Cambridge Gardens', 2);
$miner->mine('Cambridge Park', 2);
$miner->mine('Camden South', 2);
$miner->mine('Camden', 2);
$miner->mine('Camellia', 2);
$miner->mine('Cammeray', 2);
$miner->mine('Campbelltown', 2);
$miner->mine('Camperdown', 2);
$miner->mine('Campsie', 2);
$miner->mine('Canada Bay', 2);
$miner->mine('Canley Heights', 2);
$miner->mine('Canley Vale', 2);
$miner->mine('Canoelands', 2);
$miner->mine('Canterbury', 2);
$miner->mine('Caringbah South', 2);
$miner->mine('Caringbah', 2);
$miner->mine('Carlingford', 2);
$miner->mine('Carlton', 2);
$miner->mine('Carnes Hill', 2);
$miner->mine('Carramar', 2);
$miner->mine('Carss Park', 2);
$miner->mine('Cartwright', 2);
$miner->mine('Castle Cove', 2);
$miner->mine('Castle Hill', 2);
$miner->mine('Castlecrag', 2);
$miner->mine('Castlereagh', 2);
$miner->mine('Casula', 2);
$miner->mine('Catherine Field', 2);
$miner->mine('Cattai', 2);
$miner->mine('Cawdor', 2);
$miner->mine('Cecil Hills', 2);
$miner->mine('Cecil Park', 2);
$miner->mine('Centennial Park', 2);
$miner->mine('Central Business District', 2);
$miner->mine('Chatswood West', 2);
$miner->mine('Chatswood', 2);
$miner->mine('Cheltenham', 2);
$miner->mine('Cherrybrook', 2);
$miner->mine('Chester Hill', 2);
$miner->mine('Chifley', 2);
$miner->mine('Chippendale', 2);
$miner->mine('Chipping Norton', 2);
$miner->mine('Chiswick', 2);
$miner->mine('Chullora', 2);
$miner->mine('Church Point', 2);
$miner->mine('Claremont Meadows', 2);
$miner->mine('Clarendon', 2);
$miner->mine('Clareville', 2);
$miner->mine('Claymore', 2);
$miner->mine('Clemton Park', 2);
$miner->mine('Clontarf', 2);
$miner->mine('Clovelly', 2);
$miner->mine('Clyde', 2);
$miner->mine('Coasters Retreat', 2);
$miner->mine('Cobbitty', 2);
$miner->mine('Colebee', 2);
$miner->mine('Collaroy Plateau', 2);
$miner->mine('Collaroy', 2);
$miner->mine('Colyton', 2);
$miner->mine('Como', 2);
$miner->mine('Concord West', 2);
$miner->mine('Concord', 2);
$miner->mine('Condell Park', 2);
$miner->mine('Connells Point', 2);
$miner->mine('Constitution Hill', 2);
$miner->mine('Coogee', 2);
$miner->mine('Cottage Point', 2);
$miner->mine('Cowan', 2);
$miner->mine('Cranebrook', 2);
$miner->mine('Cremorne Point', 2);
$miner->mine('Cremorne', 2);
$miner->mine('Cromer', 2);
$miner->mine('Cronulla', 2);
$miner->mine('Crows Nest', 2);
$miner->mine('Croydon Park', 2);
$miner->mine('Croydon', 2);
$miner->mine('Curl Curl', 2);
$miner->mine('Currans Hill', 2);
$miner->mine('Currawong Beach', 2);
$miner->mine('Daceyville', 2);
$miner->mine('Dangar Island', 2);
$miner->mine('Darling Point', 2);
$miner->mine('Darlinghurst', 2);
$miner->mine('Darlington', 2);
$miner->mine('Davidson', 2);
$miner->mine('Dawes Point', 2);
$miner->mine('Dean Park', 2);
$miner->mine('Dee Why', 2);
$miner->mine('Denham Court', 2);
$miner->mine('Denistone East', 2);
$miner->mine('Denistone West', 2);
$miner->mine('Denistone', 2);
$miner->mine('Dharruk', 2);
$miner->mine('Dolans Bay', 2);
$miner->mine('Dolls Point', 2);
$miner->mine('Doonside', 2);
$miner->mine('Double Bay', 2);
$miner->mine('Dover Heights', 2);
$miner->mine('Drummoyne', 2);
$miner->mine('Duffys Forest', 2);
$miner->mine('Dulwich Hill', 2);
$miner->mine('Dundas Valley', 2);
$miner->mine('Dundas', 2);
$miner->mine('Dural', 2);
$miner->mine('Eagle Vale', 2);
$miner->mine('Earlwood', 2);
$miner->mine('East Gordon', 2);
$miner->mine('East Hills', 2);
$miner->mine('East Killara', 2);
$miner->mine('East Lindfield', 2);
$miner->mine('East Ryde', 2);
$miner->mine('East Sydney', 2);
$miner->mine('Eastern Creek', 2);
$miner->mine('Eastgardens', 2);
$miner->mine('Eastlakes', 2);
$miner->mine('Eastwood', 2);
$miner->mine('Edensor Park', 2);
$miner->mine('Edgecliff', 2);
$miner->mine('Edmondson Park', 2);
$miner->mine('Elanora Heights', 2);
$miner->mine('Elderslie', 2);
$miner->mine('Elizabeth Bay', 2);
$miner->mine('Elizabeth Hills', 2);
$miner->mine('Ellis Lane', 2);
$miner->mine('Elvina Bay', 2);
$miner->mine('Emerton', 2);
$miner->mine('Emu Heights', 2);
$miner->mine('Emu Plains', 2);
$miner->mine('Enfield', 2);
$miner->mine('Engadine', 2);
$miner->mine('Englorie Park', 2);
$miner->mine('Enmore', 2);
$miner->mine('Epping', 2);
$miner->mine('Ermington', 2);
$miner->mine('Erskine Park', 2);
$miner->mine('Erskineville', 2);
$miner->mine('Eschol Park', 2);
$miner->mine('Eveleigh', 2);
$miner->mine('Fairfield East', 2);
$miner->mine('Fairfield Heights', 2);
$miner->mine('Fairfield West', 2);
$miner->mine('Fairfield', 2);
$miner->mine('Fairlight', 2);
$miner->mine('Fiddletown', 2);
$miner->mine('Five Dock', 2);
$miner->mine('Flemington', 2);
$miner->mine('Forest Glen', 2);
$miner->mine('Forest Lodge', 2);
$miner->mine('Forestville', 2);
$miner->mine('Freemans Reach', 2);
$miner->mine('Frenchs Forest', 2);
$miner->mine('Freshwater', 2);
$miner->mine('Galston', 2);
$miner->mine('Georges Hall', 2);
$miner->mine('Gilead', 2);
$miner->mine('Girraween', 2);
$miner->mine('Gladesville', 2);
$miner->mine('Glebe', 2);
$miner->mine('Gledswood Hills', 2);
$miner->mine('Glen Alpine', 2);
$miner->mine('Glendenning', 2);
$miner->mine('Glenfield', 2);
$miner->mine('Glenhaven', 2);
$miner->mine('Glenmore Park', 2);
$miner->mine('Glenorie', 2);
$miner->mine('Glenwood', 2);
$miner->mine('Glossodia', 2);
$miner->mine('Gordon', 2);
$miner->mine('Granville', 2);
$miner->mine('Grasmere', 2);
$miner->mine('Grays Point', 2);
$miner->mine('Great Mackerel Beach', 2);
$miner->mine('Green Valley', 2);
$miner->mine('Greenacre', 2);
$miner->mine('Greendale', 2);
$miner->mine('Greenfield Park', 2);
$miner->mine('Greenhills Beach', 2);
$miner->mine('Greenwich', 2);
$miner->mine('Gregory Hills', 2);
$miner->mine('Greystanes', 2);
$miner->mine('Guildford West', 2);
$miner->mine('Guildford', 2);
$miner->mine('Gymea Bay', 2);
$miner->mine('Gymea', 2);
$miner->mine('Haberfield', 2);
$miner->mine('Hammondville', 2);
$miner->mine('Harrington Park', 2);
$miner->mine('Harris Park', 2);
$miner->mine('Hassall Grove', 2);
$miner->mine('Hawkesbury River', 2);
$miner->mine('Haymarket', 2);
$miner->mine('Heathcote', 2);
$miner->mine('Hebersham', 2);
$miner->mine('Heckenberg', 2);
$miner->mine('Henley', 2);
$miner->mine('Hillsdale', 2);
$miner->mine('Hinchinbrook', 2);
$miner->mine('Hobartville', 2);
$miner->mine('Holroyd', 2);
$miner->mine('Holsworthy', 2);
$miner->mine('Homebush West', 2);
$miner->mine('Homebush', 2);
$miner->mine('Horningsea Park', 2);
$miner->mine('Hornsby Heights', 2);
$miner->mine('Hornsby', 2);
$miner->mine('Horsley Park', 2);
$miner->mine('Hoxton Park', 2);
$miner->mine('Hunters Hill', 2);
$miner->mine('Huntingwood', 2);
$miner->mine('Huntleys Cove', 2);
$miner->mine('Huntleys Point', 2);
$miner->mine('Hurlstone Park', 2);
$miner->mine('Hurstville Grove', 2);
$miner->mine('Hurstville', 2);
$miner->mine('Illawong', 2);
$miner->mine('Ingleburn', 2);
$miner->mine('Ingleside', 2);
$miner->mine('Jamisontown', 2);
$miner->mine('Jannali', 2);
$miner->mine('Jordan Springs', 2);
$miner->mine('Kangaroo Point', 2);
$miner->mine('Kareela', 2);
$miner->mine('Kearns', 2);
$miner->mine('Kellyville Ridge', 2);
$miner->mine('Kellyville', 2);
$miner->mine('Kemps Creek', 2);
$miner->mine('Kensington', 2);
$miner->mine('Kenthurst', 2);
$miner->mine('Kentlyn', 2);
$miner->mine('Killara', 2);
$miner->mine('Killarney Heights', 2);
$miner->mine('Kings Cross', 2);
$miner->mine('Kings Langley', 2);
$miner->mine('Kings Park', 2);
$miner->mine('Kingsford', 2);
$miner->mine('Kingsgrove', 2);
$miner->mine('Kingswood Park', 2);
$miner->mine('Kingswood', 2);
$miner->mine('Kirkham', 2);
$miner->mine('Kirrawee', 2);
$miner->mine('Kirribilli', 2);
$miner->mine('Kogarah Bay', 2);
$miner->mine('Kogarah', 2);
$miner->mine('Kurnell', 2);
$miner->mine('Kurraba Point', 2);
$miner->mine('Kyeemagh', 2);
$miner->mine('Kyle Bay', 2);
$miner->mine('La Perouse', 2);
$miner->mine('Lakemba', 2);
$miner->mine('Lalor Park', 2);
$miner->mine('Lane Cove North', 2);
$miner->mine('Lane Cove West', 2);
$miner->mine('Lane Cove', 2);
$miner->mine('Lansdowne', 2);
$miner->mine('Lansvale', 2);
$miner->mine('Laughtondale', 2);
$miner->mine('Lavender Bay', 2);
$miner->mine('Leets Vale', 2);
$miner->mine('Leichhardt', 2);
$miner->mine('Len Waters Estate', 2);
$miner->mine('Leonay', 2);
$miner->mine('Leppington', 2);
$miner->mine('Lethbridge Park', 2);
$miner->mine('Leumeah', 2);
$miner->mine('Lewisham', 2);
$miner->mine('Liberty Grove', 2);
$miner->mine('Lidcombe', 2);
$miner->mine('Lilli Pilli', 2);
$miner->mine('Lilyfield', 2);
$miner->mine('Lindfield', 2);
$miner->mine('Linley Point', 2);
$miner->mine('Little Bay', 2);
$miner->mine('Liverpool', 2);
$miner->mine('Llandilo', 2);
$miner->mine('Loftus', 2);
$miner->mine('Londonderry', 2);
$miner->mine('Long Point', 2);
$miner->mine('Longueville', 2);
$miner->mine('Lower Portland', 2);
$miner->mine('Luddenham', 2);
$miner->mine('Lugarno', 2);
$miner->mine('Lurnea', 2);
$miner->mine('Macquarie Fields', 2);
$miner->mine('Macquarie Links', 2);
$miner->mine('Macquarie Park', 2);
$miner->mine('Maianbar', 2);
$miner->mine('Malabar', 2);
$miner->mine('Manly Vale', 2);
$miner->mine('Manly', 2);
$miner->mine('Maraylya', 2);
$miner->mine('Marayong', 2);
$miner->mine('Maroota', 2);
$miner->mine('Maroubra', 2);
$miner->mine('Marrickville', 2);
$miner->mine('Marsden Park', 2);
$miner->mine('Marsfield', 2);
$miner->mine('Mascot', 2);
$miner->mine('Matraville', 2);
$miner->mine('Mays Hill', 2);
$miner->mine('McCarrs Creek', 2);
$miner->mine('McGraths Hill', 2);
$miner->mine('McMahons Point', 2);
$miner->mine('Meadowbank', 2);
$miner->mine('Melrose Park', 2);
$miner->mine('Menai', 2);
$miner->mine('Menangle Park', 2);
$miner->mine('Merrylands West', 2);
$miner->mine('Merrylands', 2);
$miner->mine('Middle Cove', 2);
$miner->mine('Middle Dural', 2);
$miner->mine('Middleton Grange', 2);
$miner->mine('Miller', 2);
$miner->mine('Millers Point', 2);
$miner->mine('Milperra', 2);
$miner->mine('Milsons Passage', 2);
$miner->mine('Milsons Point', 2);
$miner->mine('Minchinbury', 2);
$miner->mine('Minto Heights', 2);
$miner->mine('Minto', 2);
$miner->mine('Miranda', 2);
$miner->mine('Mona Vale', 2);
$miner->mine('Monterey', 2);
$miner->mine('Moore Park', 2);
$miner->mine('Moorebank', 2);
$miner->mine('Mortdale', 2);
$miner->mine('Mortlake', 2);
$miner->mine('Mosman', 2);
$miner->mine('Mount Annan', 2);
$miner->mine('Mount Colah', 2);
$miner->mine('Mount Druitt', 2);
$miner->mine('Mount Lewis', 2);
$miner->mine('Mount Pritchard', 2);
$miner->mine('Mount Vernon', 2);
$miner->mine('Mulgoa', 2);
$miner->mine('Mulgrave', 2);
$miner->mine('Narellan Vale', 2);
$miner->mine('Naremburn', 2);
$miner->mine('Narrabeen', 2);
$miner->mine('Narraweena', 2);
$miner->mine('Narwee', 2);
$miner->mine('Nelson', 2);
$miner->mine('Neutral Bay', 2);
$miner->mine('Newington', 2);
$miner->mine('Newport', 2);
$miner->mine('Newtown', 2);
$miner->mine('Normanhurst', 2);
$miner->mine('North Balgowlah', 2);
$miner->mine('North Bondi', 2);
$miner->mine('North Curl Curl', 2);
$miner->mine('North Epping', 2);
$miner->mine('North Manly', 2);
$miner->mine('North Narrabeen', 2);
$miner->mine('North Parramatta', 2);
$miner->mine('North Richmond', 2);
$miner->mine('North Rocks', 2);
$miner->mine('North Ryde', 2);
$miner->mine('North Seaforth', 2);
$miner->mine('North St Ives', 2);
$miner->mine('North St Marys', 2);
$miner->mine('North Strathfield', 2);
$miner->mine('North Sydney', 2);
$miner->mine('North Turramurra', 2);
$miner->mine('North Wahroonga', 2);
$miner->mine('North Willoughby', 2);
$miner->mine('Northbridge', 2);
$miner->mine('Northmead', 2);
$miner->mine('Northwood', 2);
$miner->mine('Oakhurst', 2);
$miner->mine('Oakville', 2);
$miner->mine('Oatlands', 2);
$miner->mine('Oatley', 2);
$miner->mine('Old Guildford', 2);
$miner->mine('Old Toongabbie', 2);
$miner->mine('Oran Park', 2);
$miner->mine('Orchard Hills', 2);
$miner->mine('Osborne Park', 2);
$miner->mine('Oxford Falls', 2);
$miner->mine('Oxley Park', 2);
$miner->mine('Oyster Bay', 2);
$miner->mine('Paddington', 2);
$miner->mine('Padstow Heights', 2);
$miner->mine('Padstow', 2);
$miner->mine('Pagewood', 2);
$miner->mine('Palm Beach', 2);
$miner->mine('Panania', 2);
$miner->mine('Parklea', 2);
$miner->mine('Parramatta', 2);
$miner->mine('Peakhurst Heights', 2);
$miner->mine('Peakhurst', 2);
$miner->mine('Pemulwuy', 2);
$miner->mine('Pendle Hill', 2);
$miner->mine('Pennant Hills', 2);
$miner->mine('Penrith', 2);
$miner->mine('Penshurst', 2);
$miner->mine('Petersham', 2);
$miner->mine('Phillip Bay', 2);
$miner->mine('Picnic Point', 2);
$miner->mine('Pitt Town', 2);
$miner->mine('Pleasure Point', 2);
$miner->mine('Plumpton', 2);
$miner->mine('Point Piper', 2);
$miner->mine('Port Botany', 2);
$miner->mine('Potts Hill', 2);
$miner->mine('Potts Point', 2);
$miner->mine('Prairiewood', 2);
$miner->mine('Prestons', 2);
$miner->mine('Prospect', 2);
$miner->mine('Punchbowl', 2);
$miner->mine('Putney', 2);
$miner->mine('Pymble', 2);
$miner->mine('Pyrmont', 2);
$miner->mine('Quakers Hill', 2);
$miner->mine('Queens Park', 2);
$miner->mine('Queenscliff', 2);
$miner->mine('Raby', 2);
$miner->mine('Ramsgate Beach', 2);
$miner->mine('Ramsgate', 2);
$miner->mine('Randwick', 2);
$miner->mine('Redfern', 2);
$miner->mine('Regents Park', 2);
$miner->mine('Regentville', 2);
$miner->mine('Revesby Heights', 2);
$miner->mine('Revesby', 2);
$miner->mine('Rhodes', 2);
$miner->mine('Richmond', 2);
$miner->mine('Riverstone', 2);
$miner->mine('Riverview', 2);
$miner->mine('Riverwood', 2);
$miner->mine('Rockdale', 2);
$miner->mine('Rodd Point', 2);
$miner->mine('Rookwood', 2);
$miner->mine('Rooty Hill', 2);
$miner->mine('Ropes Crossing', 2);
$miner->mine('Rose Bay', 2);
$miner->mine('Rosebery', 2);
$miner->mine('Rosehill', 2);
$miner->mine('Roselands', 2);
$miner->mine('Rosemeadow', 2);
$miner->mine('Roseville Chase', 2);
$miner->mine('Roseville', 2);
$miner->mine('Rossmore', 2);
$miner->mine('Rouse Hill', 2);
$miner->mine('Royal National Park', 2);
$miner->mine('Rozelle', 2);
$miner->mine('Ruse', 2);
$miner->mine('Rushcutters Bay', 2);
$miner->mine('Russell Lea', 2);
$miner->mine('Rydalmere', 2);
$miner->mine('Ryde', 2);
$miner->mine('Sackville North', 2);
$miner->mine('Sackville', 2);
$miner->mine('Sadleir', 2);
$miner->mine('Sandringham', 2);
$miner->mine('Sans Souci', 2);
$miner->mine('Scheyville', 2);
$miner->mine('Schofields', 2);
$miner->mine('Scotland Island', 2);
$miner->mine('Seaforth', 2);
$miner->mine('Sefton', 2);
$miner->mine('Seven Hills', 2);
$miner->mine('Shalvey', 2);
$miner->mine('Shanes Park', 2);
$miner->mine('Silverwater', 2);
$miner->mine('Singletons Mill', 2);
$miner->mine('Smeaton Grange', 2);
$miner->mine('Smithfield', 2);
$miner->mine('South Coogee', 2);
$miner->mine('South Granville', 2);
$miner->mine('South Hurstville', 2);
$miner->mine('South Maroota', 2);
$miner->mine('South Penrith', 2);
$miner->mine('South Turramurra', 2);
$miner->mine('South Wentworthville', 2);
$miner->mine('South Windsor', 2);
$miner->mine('Spring Farm', 2);
$miner->mine('St Andrews', 2);
$miner->mine('St Clair', 2);
$miner->mine('St Helens Park', 2);
$miner->mine('St Ives Chase', 2);
$miner->mine('St Ives', 2);
$miner->mine('St Johns Park', 2);
$miner->mine('St Leonards', 2);
$miner->mine('St Marys', 2);
$miner->mine('St Peters', 2);
$miner->mine('Stanhope Gardens', 2);
$miner->mine('Stanmore', 2);
$miner->mine('Strathfield South', 2);
$miner->mine('Strathfield', 2);
$miner->mine('Summer Hill', 2);
$miner->mine('Surry Hills', 2);
$miner->mine('Sutherland', 2);
$miner->mine('Sydenham', 2);
$miner->mine('Sydney Olympic Park', 2);
$miner->mine('Sylvania Waters', 2);
$miner->mine('Sylvania', 2);
$miner->mine('Tamarama', 2);
$miner->mine('Taren Point', 2);
$miner->mine('Telopea', 2);
$miner->mine('Tempe', 2);
$miner->mine('Tennyson Point', 2);
$miner->mine('Terrey Hills', 2);
$miner->mine('The Ponds', 2);
$miner->mine('The Rocks', 2);
$miner->mine('Thornleigh', 2);
$miner->mine('Toongabbie', 2);
$miner->mine('Tregear', 2);
$miner->mine('Turramurra', 2);
$miner->mine('Turrella', 2);
$miner->mine('Ultimo', 2);
$miner->mine('Varroville', 2);
$miner->mine('Vaucluse', 2);
$miner->mine('Villawood', 2);
$miner->mine('Vineyard', 2);
$miner->mine('Voyager Point', 2);
$miner->mine('Wahroonga', 2);
$miner->mine('Waitara', 2);
$miner->mine('Wakeley', 2);
$miner->mine('Wallacia', 2);
$miner->mine('Wareemba', 2);
$miner->mine('Warrawee', 2);
$miner->mine('Warriewood', 2);
$miner->mine('Warwick Farm', 2);
$miner->mine('Waterfall', 2);
$miner->mine('Waterloo', 2);
$miner->mine('Watsons Bay', 2);
$miner->mine('Wattle Grove', 2);
$miner->mine('Waverley', 2);
$miner->mine('Waverton', 2);
$miner->mine('Weavers', 2);
$miner->mine('Wedderburn', 2);
$miner->mine('Wentworth Point', 2);
$miner->mine('Wentworthville', 2);
$miner->mine('Werrington County', 2);
$miner->mine('Werrington Downs', 2);
$miner->mine('Werrington', 2);
$miner->mine('West Hoxton', 2);
$miner->mine('West Killara', 2);
$miner->mine('West Lindfield', 2);
$miner->mine('West Pennant Hills', 2);
$miner->mine('West Pymble', 2);
$miner->mine('West Ryde', 2);
$miner->mine('Westleigh', 2);
$miner->mine('Westmead', 2);
$miner->mine('Wetherill Park', 2);
$miner->mine('Whalan', 2);
$miner->mine('Wheeler Heights', 2);
$miner->mine('Wiley Park', 2);
$miner->mine('Willmot', 2);
$miner->mine('Willoughby East', 2);
$miner->mine('Willoughby', 2);
$miner->mine('Windsor Downs', 2);
$miner->mine('Windsor', 2);
$miner->mine('Winston Hills', 2);
$miner->mine('Wisemans Ferry', 2);
$miner->mine('Wolli Creek', 2);
$miner->mine('Wollstonecraft', 2);
$miner->mine('Woodbine', 2);
$miner->mine('Woodcroft', 2);
$miner->mine('Woodpark', 2);
$miner->mine('Woollahra', 2);
$miner->mine('Woolloomooloo', 2);
$miner->mine('Woolooware', 2);
$miner->mine('Woolwich', 2);
$miner->mine('Woronora Heights', 2);
$miner->mine('Woronora', 2);
$miner->mine('Yagoona', 2);
$miner->mine('Yarramundi', 2);
$miner->mine('Yarrawarrah', 2);
$miner->mine('Yennora', 2);
$miner->mine('Yowie Bay', 2);
$miner->mine('Zetland', 2);